bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Melon",
    "Poppy",
    "Radish",
    "Starfruit",
    "Summer Spangle",
    "Sunflower",
    "Wheat",
    "Blueberry",
    "Coffee Bean",
    "Corn",
    "Hops",
    "Hot Pepper",
    "Tomato",
    "Spice Berry",
    "Grape",
    "Sweet Pea",
    "Red Mushroom",
    "Fiddlehead Fern",
    "Pufferfish",
    "Tuna",
    "Rainbow Trout",
    "Catfish",
    "Pike",
    "Sunfish",
    "Red Mullet",
    "Octopus",
    "Red Snapper",
    "Super Cucumber",
    "Sturgeon",
    "Tilapia",
    "Dorado",
    "Flounder",
    "Shad",
    "Halibut",
    "Crimsonfish",
];
